version: '3.8'

services:
  main:
    container_name: kyteam-main
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./package.json:/app/package.json
      - ./.env:/app/.env
    command: npm run start:dev
networks:
  default:
    name: kyteam-network