version: '3.8'

services:
  db-test:
    image: postgres:13.6
    container_name: db-test
    ports:
      - '54320:5432'
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=kyteam_db
  redis-test:
    container_name: redis-test
    image: redis:latest
    ports:
      - '63790:6379'

networks:
  default:
    name: kyteam-network
